"""
Datos iniciales de ejemplo para desarrollo.
Reemplazar con scrapers reales cuando estén listos.
"""
from datetime import datetime, timedelta

SAMPLE_DISCOUNTS = [
    # BANCOS
    {
        "title": "30% de descuento en supermercados los martes",
        "description": "Descuento en Carrefour, Coto, Jumbo y Día con tarjetas Galicia.",
        "discount_type": "descuento",
        "percentage": 30.0,
        "max_amount": 3000.0,
        "source": "Banco Galicia",
        "source_type": "banco",
        "category": "supermercados",
        "days_of_week": "martes",
        "valid_until": datetime.utcnow() + timedelta(days=30),
        "is_limited_stock": False,
        "url": "https://www.bancogalicia.com/beneficios",
        "logo_url": "https://logo.clearbit.com/bancogalicia.com",
    },
    {
        "title": "20% reintegro en combustible con Santander",
        "description": "Reintegro en YPF, Shell, Axion con tarjetas Santander.",
        "discount_type": "reintegro",
        "percentage": 20.0,
        "max_amount": 2000.0,
        "source": "Santander",
        "source_type": "banco",
        "category": "combustible",
        "days_of_week": "todos",
        "valid_until": datetime.utcnow() + timedelta(days=15),
        "is_limited_stock": False,
        "url": "https://www.santander.com.ar/beneficios",
        "logo_url": "https://logo.clearbit.com/santander.com.ar",
    },
    {
        "title": "25% OFF en farmacias los miércoles - BBVA",
        "description": "Descuento en Farmacity, Farmacity y Del Pueblo con BBVA.",
        "discount_type": "descuento",
        "percentage": 25.0,
        "max_amount": 1500.0,
        "source": "BBVA",
        "source_type": "banco",
        "category": "farmacias",
        "days_of_week": "miercoles",
        "valid_until": datetime.utcnow() + timedelta(days=2),
        "is_limited_stock": False,
        "url": "https://www.bbva.com.ar/beneficios",
        "logo_url": "https://logo.clearbit.com/bbva.com.ar",
    },
    {
        "title": "15% OFF en restaurantes - Banco Nación",
        "description": "Descuento en restaurantes adheridos con BNA.",
        "discount_type": "descuento",
        "percentage": 15.0,
        "max_amount": 2500.0,
        "source": "Banco Nación",
        "source_type": "banco",
        "category": "gastronomia",
        "days_of_week": "lunes,miercoles,viernes",
        "valid_until": datetime.utcnow() + timedelta(days=45),
        "is_limited_stock": False,
        "url": "https://www.bna.com.ar/Personas/Beneficios",
        "logo_url": "https://logo.clearbit.com/bna.com.ar",
    },
    {
        "title": "30% reintegro en indumentaria - Macro",
        "description": "Reintegro en tiendas de ropa y calzado con Macro.",
        "discount_type": "reintegro",
        "percentage": 30.0,
        "max_amount": 5000.0,
        "source": "Banco Macro",
        "source_type": "banco",
        "category": "indumentaria",
        "days_of_week": "sabado,domingo",
        "valid_until": datetime.utcnow() + timedelta(days=1),
        "is_limited_stock": True,
        "url": "https://www.macro.com.ar/beneficios",
        "logo_url": "https://logo.clearbit.com/macro.com.ar",
    },
    # FINTECHS / PREPAGAS
    {
        "title": "10% de reintegro en todos los comercios - MercadoPago",
        "description": "Reintegro pagando con saldo en cuenta de MercadoPago.",
        "discount_type": "reintegro",
        "percentage": 10.0,
        "max_amount": 1000.0,
        "source": "MercadoPago",
        "source_type": "fintech",
        "category": "todos",
        "days_of_week": "todos",
        "valid_until": datetime.utcnow() + timedelta(days=7),
        "is_limited_stock": True,
        "url": "https://www.mercadopago.com.ar/beneficios",
        "logo_url": "https://logo.clearbit.com/mercadopago.com",
    },
    {
        "title": "5% cashback en compras con Lemon",
        "description": "Cashback en crypto en todas tus compras con la tarjeta Lemon.",
        "discount_type": "reintegro",
        "percentage": 5.0,
        "max_amount": None,
        "source": "Lemon",
        "source_type": "fintech",
        "category": "todos",
        "days_of_week": "todos",
        "valid_until": datetime.utcnow() + timedelta(days=60),
        "is_limited_stock": False,
        "url": "https://lemon.me/beneficios",
        "logo_url": "https://logo.clearbit.com/lemon.me",
    },
    {
        "title": "Promoción especial supermercados - Naranja X",
        "description": "30% OFF los jueves en supermercados con NaranjaX.",
        "discount_type": "descuento",
        "percentage": 30.0,
        "max_amount": 2000.0,
        "source": "Naranja X",
        "source_type": "fintech",
        "category": "supermercados",
        "days_of_week": "jueves",
        "valid_until": datetime.utcnow() + timedelta(days=20),
        "is_limited_stock": False,
        "url": "https://www.naranjax.com/beneficios",
        "logo_url": "https://logo.clearbit.com/naranjax.com",
    },
    {
        "title": "Descuento en viajes con MODO",
        "description": "20% OFF en plataformas de turismo pagando con MODO.",
        "discount_type": "descuento",
        "percentage": 20.0,
        "max_amount": 10000.0,
        "source": "MODO",
        "source_type": "fintech",
        "category": "viajes",
        "days_of_week": "todos",
        "valid_until": datetime.utcnow() + timedelta(days=3),
        "is_limited_stock": True,
        "url": "https://www.modo.com.ar/beneficios",
        "logo_url": "https://logo.clearbit.com/modo.com.ar",
    },
]
